# Generated by Django 4.2 on 2023-04-24 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0004_profissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='profissão',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CadastroCliente.profissao'),
        ),
    ]
