# Generated by Django 4.2 on 2023-04-24 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0005_cliente_profissão'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='profissão',
            new_name='profissao',
        ),
    ]
