# Generated by Django 4.2 on 2023-04-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0008_interesse_cliente_interesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=250, null=True, verbose_name='endereco'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='matricula',
            field=models.IntegerField(verbose_name='Matricula'),
        ),
    ]
